import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className={styles.bodyWrapper}>
          <header className={styles.header}>
            <div className={styles.navContainer}>
              <div className={styles.logoWrapper}>
                <span className={styles.logoText}>CodeCamp</span>
                <span className={styles.logoSubtext}>Next.js Course</span>
              </div>
              {/* Nav */}
              <nav className={styles.nav}>
                <Link href={"/"} className={styles.navLink}>
                  Home
                </Link>
                <Link href={"/about"} className={styles.navLink}>
                  About
                </Link>
                <Link href={"/dashboard"} className={styles.navLink}>
                  Dashboard
                </Link>
                <Link href={"/products"} className={styles.navLink}>
                  Products
                </Link>
                <Link href={"/news"} className={styles.navLink}>
                  News
                </Link>
              </nav>
            </div>
          </header>

          <main className={styles.main}>{children}</main>

          <footer className={styles.footer}>
            <p>&copy; 2026 CoCamp. All right reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
